module.exports = {
    RAKUTEN_KUJI_APK_VERSION: 'v7.3.2',
    RAKUTEN_KUJI_APK_NAME: 'R_Kuji.apk',
    RAKUTEN_POINT_CLUB_APK_VERSION: 'v6.6.0',
    RAKUTEN_RECIPE_APK_VERSION: 'v4.7',
    RAKUTEN_SUPER_POINT_SCREEN_APK_VERSION: 'v8.15.0',
    RAKUTEN_SUPER_POINT_SCREEN_APK_NAME: 'R_SuperPointScreen.apk',
    RAKUTEN_TOSHIRU_APK_VERSION: 'v2.0.4',
}
