export default {
    RAKUTEN_USERNAME: process.env.RAKUTEN_USERNAME || '',
    RAKUTEN_PASSWORD: process.env.RAKUTEN_PASSWORD || '',
    LOGIN_PAGE: 'https://kuji.rakuten.co.jp/256356cd1a',
    WEBSEARCH_SEARCH_PAGE: 'https://websearch.rakuten.co.jp/Web?qt=test&col=OW',
    WEBSEARCH_SEARCH_HOME_PAGE: 'https://websearch.rakuten.co.jp',
    WEBSEARCH_MAX_COUNT: 7,
    WEBSEARCH_PREFIX: '寿司',
    KUJI_HOME_PAGE: 'https://kuji.rakuten.co.jp',
    KUJI_DEFAULT_LINK: [
        'https://www.rakuten-card.co.jp/point/pointsave/janken/redirect/?l-id=corp_oo_janken_win-redirect',
        'https://www.rakuten-card.co.jp/point/pointsave/sakana-quiz/redirect/?l-id=corp_oo_sakanaquiz_win-redirect',
        'https://www.rakuten-card.co.jp/point/pointsave/takara-sagashi/redirect/?l-id=corp_oo_takara_sagashi_win-redirect',
        'https://www.rakuten-card.co.jp/e-navi/members/other-services/lucky-lot/redirect.xhtml?l-id=enavi_top_info-personal_lucky-lot',
        'https://kuji.rakuten.co.jp/256356cd1a',
        'https://kuji.rakuten.co.jp/8212abcffe',
        'https://kuji.rakuten.co.jp/fae37d0d91',
        'https://kuji.rakuten.co.jp/d2b37c7d6a',
        'https://kuji.rakuten.co.jp/9d91da42ab',
        'https://kuji.rakuten.co.jp/33d38332c2',
        'https://kuji.rakuten.co.jp/1f43825712',
        'https://kuji.rakuten.co.jp/6c238469a1',
        'https://kuji.rakuten.co.jp/71f38444b5',
        'https://kuji.rakuten.co.jp/5103830522',
        'https://kuji.rakuten.co.jp/4263816d7f',
        'https://kuji.rakuten.co.jp/ffc1c52299',
        'https://kuji.rakuten.co.jp/14d330d3e0',
        'https://kuji.rakuten.co.jp/4e9371dd92',
        'https://kuji.rakuten.co.jp/81137ce423',
        'https://kuji.rakuten.co.jp/bc23814a75',
        'https://kuji.rakuten.co.jp/8c538152dd',
        'https://kuji.rakuten.co.jp/4dd381bac9',
        'https://kuji.rakuten.co.jp/9ea32a8dfa',
        'https://kuji.rakuten.co.jp/ad1321af05',
        'https://kuji.rakuten.co.jp/4ad36145c2',
        'https://kuji.rakuten.co.jp/1243541a35',
        'https://kuji.rakuten.co.jp/1a638459e0',
        'https://kuji.rakuten.co.jp/066385a922',
        'https://kuji.rakuten.co.jp/f3a3832d0c',
        'https://kuji.rakuten.co.jp/494387e1e2',
        'https://kuji.rakuten.co.jp/2c5388f246',
        'https://kuji.rakuten.co.jp/62838922a0',
    ],
    RAKUTENCARD_HOME_PAGE: 'https://www.rakuten-card.co.jp/e-navi/members/index.xhtml',
    DAY_VIEW_VIDEO_GET_POINT: 20,
    CAMPAIGN_PAGE_LIST: [
        'https://event.rakuten.co.jp/campaign/card/pointday',
        'https://event.rakuten.co.jp/campaign/sports',
        'https://event.rakuten.co.jp/campaign/rank/point',
        'https://event.rakuten.co.jp/group/sbc',
    ],
    DEFAULT_TIMEOUT: 15000,
    DEFAULT_KUJI_PAGE_TIMEOUT: 2 * 60000,
    BANK_LOGIN_PAGE: 'https://www.rakuten-bank.co.jp/present/',
    BANK_RAKUTEN_USERNAME: process.env.BANK_RAKUTEN_USERNAME || '',
    BANK_RAKUTEN_PASSWORD: process.env.BANK_RAKUTEN_PASSWORD || '',
}
