export default {
    RAKUTEN_USERNAME: process.env.RAKUTEN_USERNAME || '',
    RAKUTEN_PASSWORD: process.env.RAKUTEN_PASSWORD || '',
    LOGIN_PAGE: 'https://kuji.rakuten.co.jp/256356cd1a',
    WEBSEARCH_SEARCH_PAGE: 'https://websearch.rakuten.co.jp/Web?qt=test&col=OW',
    WEBSEARCH_MAX_COUNT: 30,
    WEBSEARCH_PREFIX: '魚',
    KUJI_HOME_PAGE: 'https://kuji.rakuten.co.jp',
    KUJI_DEFAULT_LINK: [
        'https://kuji.rakuten.co.jp/256356cd1a',
        'https://kuji.rakuten.co.jp/8212abcffe',
        'https://kuji.rakuten.co.jp/fae37d0d91',
        'https://kuji.rakuten.co.jp/d2b37c7d6a',
        'https://kuji.rakuten.co.jp/9d91da42ab',

        'https://kuji.rakuten.co.jp/ffc1c52299',
        'https://kuji.rakuten.co.jp/14d330d3e0',
        'https://kuji.rakuten.co.jp/4e9371dd92',
        'https://kuji.rakuten.co.jp/81137ce423',
        'https://kuji.rakuten.co.jp/bc23814a75',
        'https://kuji.rakuten.co.jp/8c538152dd',
        'https://kuji.rakuten.co.jp/4dd381bac9',
        'https://kuji.rakuten.co.jp/9ea32a8dfa',
    ],
    RAKUTENCARD_HOME_PAGE: 'https://www.rakuten-card.co.jp/e-navi/index.xhtml',
}