export default {
  RAKUTEN_USERNAME: process.env.RAKUTEN_USERNAME || "",
  RAKUTEN_PASSWORD: process.env.RAKUTEN_PASSWORD || "",
  LOGIN_PAGE: "https://grp02.id.rakuten.co.jp/rms/nid/login?service_id=c11",
  WEBSEARCH_SEARCH_PAGE: "https://websearch.rakuten.co.jp/Web?qt=test&col=OW",
  WEBSEARCH_SEARCH_HOME_PAGE: "https://websearch.rakuten.co.jp",
  WEBSEARCH_MAX_COUNT: 7,
  WEBSEARCH_PREFIX: "天ぷら",
  KUJI_HOME_PAGE: "https://kuji.rakuten.co.jp",
  KUJI_DEFAULT_LINK: [
    // https://bakkuappu.seesaa.net/
    // $$('.entryBody毎日引けるくじ > a:nth-child(1)').map(a => a.href)
    // $$('.entryBody一回だけ引けるくじ > a:nth-child(1)').map(a => a.href)
    // $$('.entryBodyその他 > a').map(a => a.href)
    // https://rakucoin.appspot.com/rakuten/kuji/
    "https://kuji.rakuten.co.jp/137451f19b",
    "https://kuji.rakuten.co.jp/d594527fa8",
    "https://kuji.rakuten.co.jp/2b64526145",
    "https://kuji.rakuten.co.jp/df6450f8c7",
    "https://kuji.rakuten.co.jp/69144b32de",
    "https://kuji.rakuten.co.jp/56c4519469",
    "https://kuji.rakuten.co.jp/244450dda0",
    "https://kuji.rakuten.co.jp/efa450c162",
    "https://kuji.rakuten.co.jp/2b544902af",
    "https://kuji.rakuten.co.jp/f71449eabf",
    "https://kuji.rakuten.co.jp/d22446cdfc",
    "https://kuji.rakuten.co.jp/15a44600fb",
    "https://kuji.rakuten.co.jp/58544080d9",
    "https://kuji.rakuten.co.jp/d19440766e",
    "https://kuji.rakuten.co.jp/2e743a82e5",
    "https://kuji.rakuten.co.jp/1e842a2ecd",
    "https://kuji.rakuten.co.jp/a8c429047d",
    "https://personal-finance.rakuten.co.jp/kuji/ref.html",
    "https://kuji.rakuten.co.jp/86c40aca5f",
    "https://kuji.rakuten.co.jp/d6e3c174e6",
    "https://point.rakuten.co.jp/doc/tametokumodekuji/",
    "https://kuji.rakuten.co.jp/2c43c18483",
    "https://kuji.rakuten.co.jp/7e14010b80",
    "https://kuji.rakuten.co.jp/1243541a35",
    "https://kuji.rakuten.co.jp/4351057845",
    "https://www.infoseek.co.jp/mission/list/",
    "https://kuji.rakuten.co.jp/ef23be45f7",
    "https://kuji.rakuten.co.jp/5f93b1fd01",
    "https://pointmall.rakuten.co.jp/gacha",
    "https://kuji.rakuten.co.jp/9763988951",
    "https://kuji.rakuten.co.jp/fc437af2c7",
    "https://kuji.rakuten.co.jp/e7a37ae390",
    "https://kuji.rakuten.co.jp/26e390eccf",
    "https://kuji.rakuten.co.jp/c5337832c5",
    "https://kuji.rakuten.co.jp/38c3861fdc",
    "https://kuji.rakuten.co.jp/889373540e",
    "https://kuji.rakuten.co.jp/c8437c01c5",
    "https://kuji.rakuten.co.jp/26d37b04b2",
    "https://kuji.rakuten.co.jp/42136c5d7d",
    "https://kuji.rakuten.co.jp/7393386d27",
    "https://kuji.rakuten.co.jp/14d330d3e0",
    "https://kuji.rakuten.co.jp/6e7329f994",
    "https://kuji.rakuten.co.jp/9ea32a8dfa",
    "https://kuji.rakuten.co.jp/34e2cb79fa",
    "https://kuji.rakuten.co.jp/46211bf9dd",
    "https://kuji.rakuten.co.jp/18584163d",
    "https://kuji.rakuten.co.jp/12044f7678",
    "https://kuji.rakuten.co.jp/f3c44dfe88",
    "https://kuji.rakuten.co.jp/daa44f3f92",
    "https://kuji.rakuten.co.jp/7da44f9512",
    "https://kuji.rakuten.co.jp/3f944da48c",
    "https://kuji.rakuten.co.jp/a5044805fb",
    "http://recipe.rakuten.co.jp/sp1/kuji/top/",
    "https://point-g.r10s.jp/ref/lucky_kuji_calendar.html",
    "http://r10.to/hGFzlQ",
    "http://r10.to/hs6eho",
    "https://dining.rakuten.co.jp/campaign/kuji/",
    "https://www.rebates.jp/poikatsu",
    "https://www.rakuten-card.co.jp/minna-money/",
    "https://books.rakuten.co.jp/event/e-book/camp-luckykuji/",
    "https://magazine.rakuten.co.jp/cpn/app/index.html",
    "https://flyer.screen.rakuten.co.jp/flyers/",
    "https://one.rakuten.co.jp/lp/otoku/campaign.html?scid=wi_link_otokukuji_after_lottery_finished#kujiArea",
    "http://event.rakuten.co.jp/campaign/point-up/marathon/",
    "http://event.rakuten.co.jp/campaign/supersale",
    "https://event.rakuten.co.jp/brand/campaign/",
    "https://event.rakuten.co.jp/brand/campaign/kuji/",
    "https://event.rakuten.co.jp/campaign/pointback/",
    "http://event.rakuten.co.jp/campaign/sports/",
    "https://coupon.rakuten.co.jp/",
    "https://coupon.rakuten.co.jp/assets/inc/kuji_redirect.html",
    "http://event.rakuten.co.jp/newyear/",
    "https://event.rakuten.co.jp/newyear/omikuji/",
    "https://event.rakuten.co.jp/valentine/",
    "https://event.rakuten.co.jp/valentine/campaign/lottery/",
    "https://event.rakuten.co.jp/season/newlife/",
    "https://event.rakuten.co.jp/season/newlife/campaign/lottery/",
    "https://event.rakuten.co.jp/whiteday/",
    "https://event.rakuten.co.jp/whiteday/special/kuji/",
    "https://event.rakuten.co.jp/mother/",
    "https://event.rakuten.co.jp/mother/special/lottery/",
    "https://event.rakuten.co.jp/father/",
    "https://event.rakuten.co.jp/father/special/lottery/",
    "http://event.rakuten.co.jp/ochugen/",
    "https://event.rakuten.co.jp/ochugen/lottery/",
    "https://event.rakuten.co.jp/keirou/",
    "https://event.rakuten.co.jp/keirou/campaign/kuji/",
    "https://event.rakuten.co.jp/halloween/",
    "https://event.rakuten.co.jp/season/awlife/",
    "https://event.rakuten.co.jp/season/awlife/special/lottery/",
    "https://event.rakuten.co.jp/campaign/eagles/",
    "https://event.rakuten.co.jp/toshikoshi/",
    "https://event.rakuten.co.jp/toshikoshi/kuji/",
    "https://event.rakuten.co.jp/oseibo/",
    "https://event.rakuten.co.jp/oseibo/theme/lottery/",
    "https://event.rakuten.co.jp/xmas/",
    "https://event.rakuten.co.jp/xmas/special/kuji/",
    "https://event.rakuten.co.jp/campaign/point-up/blackfriday/",
    "https://event.rakuten.co.jp/campaign/vissel/thanks/",
    "http://event.rakuten.co.jp/campaign/thanks/",
    "https://event.rakuten.co.jp/newyear/pre/",
    "https://event.rakuten.co.jp/newyear/luckylottery/",
    "https://app.kuji.rakuten.co.jp/campaign/poikatu/kuji/kuji202606.html",
    "https://rakucoin.appspot.com/rakuten/kuji/redirect/2b544902af",
    "https://rakucoin.appspot.com/rakuten/kuji/redirect/fc437af2c7",
    "https://kuji.rakuten.co.jp/e5741cf5af",
    "https://rakucoin.appspot.com/rakuten/kuji/redirect/e7a37ae390",
    "https://pointmall.rakuten.co.jp/janken",
    "https://pointmall.rakuten.co.jp/omikuji",
    "https://pointmall.rakuten.co.jp/scratch",
  ],
  RAKUTENCARD_HOME_PAGE:
    "https://www.rakuten-card.co.jp/e-navi/members/index.xhtml",
  DAY_VIEW_VIDEO_GET_POINT: 20,
  CAMPAIGN_PAGE_LIST: [
    "https://event.rakuten.co.jp/campaign/card/pointday",
    "https://event.rakuten.co.jp/campaign/sports",
    "https://event.rakuten.co.jp/campaign/rank/point",
    "https://event.rakuten.co.jp/group/sbc",
  ],
  DEFAULT_TIMEOUT: 5000,
  DEFAULT_KUJI_PAGE_TIMEOUT: 2 * 30000,
  BANK_LOGIN_PAGE: "https://www.rakuten-bank.co.jp/present/",
  BANK_RAKUTEN_USERNAME: process.env.BANK_RAKUTEN_USERNAME || "",
  BANK_RAKUTEN_PASSWORD: process.env.BANK_RAKUTEN_PASSWORD || "",
  INFO_SEEK_PAGE: "https://www.infoseek.co.jp",
  INFO_SEEK_MISSION_PAGE: "https://www.infoseek.co.jp/mission/list/",
  DEFAULT_READ_ARTICLE_TIME: 12000,
  READ_ARTICLE_MAX_COUNT: 5,
  INFO_SEEK_RANKING_PAGE: [
    "https://news.infoseek.co.jp/ranking/",
    "https://news.infoseek.co.jp/ranking/entertainment",
    "https://news.infoseek.co.jp/ranking/poli-soci",
    "https://news.infoseek.co.jp/ranking/sports",
    "https://news.infoseek.co.jp/ranking/busi-econ",
    "https://news.infoseek.co.jp/ranking/world",
    "https://news.infoseek.co.jp/ranking/it",
    "https://news.infoseek.co.jp/ranking/life",
  ],
  INFO_SEEK_MISSION_VISIT_PAGE: "https://www.infoseek.co.jp/mission/visit",
};
