name: Appium CI

on:
  push:
    branches:
      - rakuten_apps
    paths:
    - "test/**.ts"
    - "apps/**.apk"
  workflow_dispatch:

jobs:
  kuji:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install Appium
      uses: FinbertMDS/setup-appium@latest
    - name: Install UIAutomator
      run: appium driver install uiautomator2
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      env:
        RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
        RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
      with:
        api-level: 29
        target: google_apis
        script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:kuji)"
    - name: upload-artifact
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: upload-screenshots-kuji
        path: screenshots
    - name: remove-screenshots
      if: ${{ failure() }}
      run: rm -rf ./screenshots

  pointclub:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install Appium
      uses: FinbertMDS/setup-appium@latest
    - name: Install UIAutomator
      run: appium driver install uiautomator2
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      env:
        RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
        RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
      with:
        api-level: 29
        target: google_apis
        script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:pointclub)"
    - name: upload-artifact
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: upload-screenshots-pointclub
        path: screenshots
    - name: remove-screenshots
      if: ${{ failure() }}
      run: rm -rf ./screenshots

  # recipe:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: 20
  #       cache: 'yarn'
  #   - name: Install Appium
  #     uses: FinbertMDS/setup-appium@latest
  #   - name: Install UIAutomator
  #     run: appium driver install uiautomator2
  #   - name: Install dependencies
  #     run: yarn install --frozen-lockfile
  #   - name: Run Appium Tests
  #     uses: reactivecircus/android-emulator-runner@v2
  #     env:
  #       RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
  #       RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
  #     with:
  #       api-level: 29
  #       target: google_apis
  #       script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:recipe)"
  #   - name: upload-artifact
  #     if: ${{ failure() }}
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: upload-screenshots-recipe
  #       path: screenshots
  #   - name: remove-screenshots
  #     if: ${{ failure() }}
  #     run: rm -rf ./screenshots

  superpointscreen:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install Appium
      uses: FinbertMDS/setup-appium@latest
    - name: Install UIAutomator
      run: appium driver install uiautomator2
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      env:
        RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
        RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
      with:
        api-level: 29
        target: google_apis
        script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:superpointscreen)"
    - name: upload-artifact
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: upload-screenshots-superpointscreen
        path: screenshots
    - name: remove-screenshots
      if: ${{ failure() }}
      run: rm -rf ./screenshots

  toshiru:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Install Appium
      uses: FinbertMDS/setup-appium@latest
    - name: Install UIAutomator
      run: appium driver install uiautomator2
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      env:
        RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
        RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
      with:
        api-level: 29
        target: google_apis
        script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:toshiru)"
    - name: upload-artifact
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: upload-screenshots-toshiru
        path: screenshots
    - name: remove-screenshots
      if: ${{ failure() }}
      run: rm -rf ./screenshots

  # pointclub_toshiru:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: 20
  #       cache: 'yarn'
  #   - name: Install Appium
  #     uses: FinbertMDS/setup-appium@latest
  #   - name: Install UIAutomator
  #     run: appium driver install uiautomator2
  #   - name: Install dependencies
  #     run: yarn install --frozen-lockfile
  #   - name: Run Appium Tests
  #     uses: reactivecircus/android-emulator-runner@v2
  #     env:
  #       RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
  #       RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
  #     with:
  #       api-level: 29
  #       target: google_apis
  #       script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || (sleep 60 && yarn test:pointclub_toshiru)"
  #   - name: upload-artifact
  #     if: ${{ failure() }}
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: upload-screenshots-pointclub_toshiru
  #       path: screenshots
  #   - name: remove-screenshots
  #     if: ${{ failure() }}
  #     run: rm -rf ./screenshots