name: Appium CI

on:
  push:
    branches:
      - rakuten_apps
    paths:
    - "test/**"
    - ".github/workflows/app.ci.yml"

jobs:
  build:
    env:
      RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
      RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install and Run Appium Server
      run: |
        chmod +x ./scripts/RunAppiumServer.sh
        ./scripts/RunAppiumServer.sh
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: "[-z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || yarn test"
