name: Selenium JavaScript Mocha CI

on:
  push:
    branches:
      - developer
  schedule:
    - cron:  '30 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine

    steps:
    - uses: actions/checkout@v2 # Checkout the code
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: ueokande/setup-firefox@latest
    - run: firefox --version
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
        chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
    # - run: |
    #     yarn global add selenium-side-runner chromedriver geckodriver
    #     echo "$(yarn global bin)" >> $GITHUB_PATH
    # - run: |
    #     testfiles="$(pwd)""/*.side"
    #     selenium-side-runner $testfiles -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]"
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - run: yarn test
      env:
        RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
        RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
