name: Daily

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    if: (github.event_name == 'schedule')
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'developer'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Test
      run: ([ -z $RAKUTEN_USERNAME ] || [ -z $RAKUTEN_PASSWORD ] || yarn test)
      env:
        RAKUTEN_USERNAME: ${{ secrets.RAKUTEN_USERNAME }}
        RAKUTEN_PASSWORD: ${{ secrets.RAKUTEN_PASSWORD }}
    - name: upload-artifact
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: upload-screenshots
        path: screenshots
    - name: remove-screenshots
      if: ${{ failure() }}
      run: rm -rf ./screenshots

  ##################################
  ### Run when a schedule failed ###
  ##################################
  restart_when_failed:
    name: Restarts the scheduled run when it failed
    runs-on: ubuntu-18.04
    if: github.event_name == 'schedule' && failure()
    needs: [build]
    steps:
      - name: Retry the workflow
        run: |
          curl -i \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
          https://api.github.com/repos/FinbertMDS/receive_rakuten_point/actions/workflows/6691016/dispatches \
          -d '{"ref": "${{ github.ref }}" }'
